# Generated by Django 5.2.9 on 2026-02-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_remove_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'admin'), ('faculty', 'faculty'), ('corporate-trainer', 'corporaate-trainer')], default='student', max_length=20),
        ),
    ]
