# Generated by Django 5.2.9 on 2026-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
